apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tennis-arranger-frontend-prod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        env: prod
        app: tennis-arranger-frontend
    spec:
      containers:
        - name: tennis-arranger-frontend-prod
          image: docker.io/justinrickard/tennis-arranger-frontend-prod:0.0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: dockerhub-docker-registry
