apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "justin-5d49"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "justin-5d49"
    spec:
      containers:
        - name: "justin-5d49"
          image: "justin.azurecr.io/justin"
          ports:
          - containerPort: 80