apiVersion: v1
kind: Service
metadata:
    name: "justin-5d49"
    labels:
        app: "justin-5d49"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "justin-5d49"