apiVersion: v1
kind: Service
metadata:
  labels:
    env: dev
    app: tennis-arranger-frontend
  name: tennis-arranger-frontend-dev
spec:
  type: ClusterIP
  ports:
  - name: service-port-name
    port: 80
    protocol: TCP
  selector:
    matchLabels:
      env: dev
      app: tennis-arranger-frontend
