apiVersion: v1
kind: Service
metadata:
  labels:
    env: dev
    app: tennis-arranger-frontend
  name: tennis-arranger-frontend-dev
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    env: dev
    app: tennis-arranger-frontend
